### ISSUE TITLE
No locks available

### ISSUE THREAD

**Issue by lkp520** [csjliang/LPTN#29]
When I run PYTHONPATH="/data/likengpeng/LPTN/" python scripts/data_preparation/create_lmdb.py, I meet the problem:
Reading image path list ...
Create lmdb for datasets/FiveK/FiveK_480p/train/A, save to datasets/FiveK/FiveK_train_source.lmdb...
Totoal images: 2250
Data size per image is:  482882
Traceback (most recent call last):
  File "/data/likengpeng/LPTN/scripts/data_preparation/create_lmdb.py", line 39, in <module>
    create_lmdb()
  File "/data/likengpeng/LPTN/scripts/data_preparation/create_lmdb.py", line 10, in create_lmdb
    make_lmdb_from_imgs(folder_path, lmdb_path, img_path_list, keys)
  File "/data/likengpeng/LPTN/codes/utils/lmdb_util.py", line 107, in make_lmdb_from_imgs
    env = lmdb.open(lmdb_path, map_size=map_size)
lmdb.Error: datasets/FiveK/FiveK_train_source.lmdb: No locks available

How can I solve it? Thank you!

**Comment by csjliang** [comment]
Sorry for the late reply. Please check the environment since others can run successfully. If not, you can also run the program without lmdb (maybe slightly slower).
