### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__buffer__'

### ISSUE THREAD

**Issue by chenyuanpengcyp** [csjliang/LPTN#4]
Hi, I am running the single training script. The program has such an error:
```
  File "codes/train.py", line 250, in <module>
    main()
  File "codes/train.py", line 179, in main
    prefetcher = CUDAPrefetcher(train_loader, opt)
  File "/data/code_fusion/Pytorch-LPTN/LPTN-main/codes/data/prefetch_dataloader.py", line 103, in __init__
    self.preload()
  File "/data/code_fusion/Pytorch-LPTN/LPTN-main/codes/data/prefetch_dataloader.py", line 109, in preload
    self.batch = next(self.loader)  # self.batch is a dict
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chenyuanpeng/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/code_fusion/Pytorch-LPTN/LPTN-main/codes/data/unpair_image_dataset.py", line 53, in __getitem__
    img_gt = imfrombytes(img_bytes, float32=True)
  File "/data/code_fusion/Pytorch-LPTN/LPTN-main/codes/utils/img_util.py", line 166, in imfrombytes
    img_np = np.frombuffer(content, np.uint8)
AttributeError: 'NoneType' object has no attribute '__buffer__'
```
but, the number of the data in the input log is not 0.

```
2021-05-21 10:48:20,393 INFO: Dataset UnPairedImageDataset - FiveK is created.
2021-05-21 10:48:20,393 INFO: Training statistics:
	Number of train images: 2250
	Dataset enlarge ratio: 100
	Batch size per gpu: 32
	World size (gpu number): 1
	Require iter number per epoch: 7032
	Total epochs: 43; iters: 300000.
2021-05-21 10:48:20,460 INFO: Dataset PairedImageDataset - FiveK_val is created.
2021-05-21 10:48:20,460 INFO: Number of val images/folders in FiveK_val: 500
```

**Comment by csjliang** [comment]
Hi, this issue might be caused by the version mismatch of torchvision or torch. You may need to degrade one of them. Thanks.

**Comment by 24werewolf** [comment]
> Hi, this issue might be caused by the version mismatch of torchvision or torch. You may need to degrade one of them. Thanks.
My torch version 1.7.1 ,  torchvision version 0.8.2

if it is caused by the version mismatch of torchvision or torch, bu I can run other pytorch code.

**Comment by chenyuanpengcyp** [comment]
> Hi, this issue might be caused by the version mismatch of torchvision or torch. You may need to degrade one of them. Thanks.


Thanks for your reply
My torch version 1.7.1 , torchvision version 0.8.2
if it is caused by the version mismatch of torchvision or torch, bu I can run other pytorch code.

**Comment by csjliang** [comment]
> > Hi, this issue might be caused by the version mismatch of torchvision or torch. You may need to degrade one of them. Thanks.
> 
> Thanks for your reply
> My torch version 1.7.1 , torchvision version 0.8.2
> if it is caused by the version mismatch of torchvision or torch, bu I can run other pytorch code.

I think the version of your torchvision is too high for this code. Please degrade it or create a new env with lower torchvision. Thanks.

**Comment by chenyuanpengcyp** [comment]
> > > Hi, this issue might be caused by the version mismatch of torchvision or torch. You may need to degrade one of them. Thanks.
> > 
> > 
> > Thanks for your reply
> > My torch version 1.7.1 , torchvision version 0.8.2
> > if it is caused by the version mismatch of torchvision or torch, bu I can run other pytorch code.
> 
> I think the version of your torchvision is too high for this code. Please degrade it or create a new env with lower torchvision. Thanks.

Thanks for your reply. I will try

It is work !! Thanks !!
